import React, { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { LANGUAGE_STORAGE_KEY, resolveLocale, type Locale } from "@/lib/languagePreference";

type TranslationValues = Record<string, string | number>;

const messages = {
  en: {
    "language.label": "Language",
    "language.russian": "Русский",
    "language.english": "English",
    "theme.toDark": "Switch to dark mode",
    "theme.toLight": "Switch to light mode",
    "common.dashboard": "Dashboard",
    "common.loading": "Loading…",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.back": "Back",
    "auth.signupTitle": "Create your account",
    "auth.signinTitle": "Welcome back",
    "auth.signupDescription": "Start building your portfolio in a secure workspace.",
    "auth.signinDescription": "Sign in to continue working on your portfolio.",
    "auth.name": "Name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.signup": "Create account",
    "auth.signin": "Sign in",
    "auth.wait": "Please wait…",
    "auth.hasAccount": "Already have an account?",
    "auth.noAccount": "New to Portfolio Pro?",
    "auth.verifyEmail": "Check your email, confirm your address, then sign in to Portfolio Pro.",
    "auth.invalidEmail": "Enter a valid email address.",
    "auth.passwordLength": "Password must contain at least 8 characters.",
    "auth.nameLength": "Enter a name with at least 2 characters.",
    "auth.invalidData": "Check the information you entered.",
    "auth.runtimeError": "This form is only available in the external Supabase runtime.",
    "auth.requestError": "We could not complete authentication.",
    "landing.login": "Log in",
    "landing.start": "Start building",
    "landing.eyebrow": "The portfolio builder for considered work",
    "landing.titleBefore": "Present your work with",
    "landing.titleAccent": "clarity.",
    "landing.description": "A quietly powerful canvas for designers, creators, and independent studios. Build a portfolio that is unmistakably yours.",
    "landing.create": "Create your portfolio",
    "landing.how": "See how it works",
    "landing.noCode": "No code required",
    "landing.publish": "Publish in minutes",
    "landing.evolve": "Designed to evolve",
    "landing.sectionEyebrow": "Made for the work behind the work",
    "landing.sectionTitle": "A focused space to make a strong first impression.",
    "landing.featureLayoutsTitle": "Four considered layouts",
    "landing.featureLayoutsText": "Minimal, Gallery, Cards, and Blog — each calibrated for a different creative voice.",
    "landing.featureVisualTitle": "Your visual language",
    "landing.featureVisualText": "Fine-tune colour, typography, biography, and social links without touching a line of code.",
    "landing.featureControlTitle": "Always in control",
    "landing.featureControlText": "See edits reflected instantly, review them with confidence, and save when you are ready.",
    "dashboard.unauthTitle": "Your workspace awaits.",
    "dashboard.unauthDescription": "Sign in to create and manage your published work.",
    "dashboard.continueEmail": "Continue with email",
    "dashboard.continueManus": "Continue with Manus",
    "dashboard.logout": "Log out",
    "dashboard.portfolios": "Portfolios",
    "dashboard.sidebarTitle": "Make it unmistakably yours.",
    "dashboard.sidebarDescription": "Add a short bio, a memorable URL and visual language.",
    "dashboard.eyebrow": "Your workspace",
    "dashboard.descriptionEmpty": "A home for the work you want to be remembered by.",
    "dashboard.descriptionCount": "{count} portfolio(s) in your studio.",
    "dashboard.create": "New portfolio",
    "dashboard.creating": "Creating…",
    "dashboard.loadError": "We couldn’t load your portfolios. Please refresh and try again.",
    "dashboard.deleteConfirm": "Delete this portfolio? This cannot be undone.",
    "dashboard.emptyTitle": "Start with a clean canvas.",
    "dashboard.emptyDescription": "Create your first portfolio, then make it feel like yours in the live editor.",
    "dashboard.createFirst": "Create portfolio",
    "dashboard.createError": "We could not open the new portfolio.",
    "editor.saved": "Changes saved",
    "editor.cancel": "Cancel",
    "editor.saving": "Saving",
    "editor.save": "Save",
    "editor.notFound": "This portfolio could not be found.",
    "editor.backDashboard": "Back to dashboard",
    "editor.untitled": "Untitled portfolio",
    "editor.projects": "Projects",
    "editor.view": "View",
    "editor.uploading": "Uploading",
    "editor.profileTitle": "Your profile",
    "editor.profileDescription": "Shape the story visitors meet first.",
    "editor.portfolioTitle": "Portfolio title",
    "editor.biography": "Biography",
    "editor.avatar": "Avatar",
    "editor.logo": "Logo",
    "editor.publicUrl": "Public URL",
    "editor.publicUrlDescription": "Generated from your name, or make it your own.",
    "editor.artDirection": "Art direction",
    "editor.artDescription": "Every selection is reflected on the right, instantly.",
    "editor.template": "Template",
    "editor.colorScheme": "Color scheme",
    "editor.typography": "Typography",
    "editor.socialLinks": "Social links",
    "editor.socialDescription": "Add up to five places to find you.",
    "editor.add": "Add",
    "editor.removeSocial": "Remove social link",
    "editor.publish": "Publish this portfolio",
    "editor.publishDescription": "When turned off, your public URL returns a 404 page.",
    "editor.completeUpload": "Finish the image upload before saving changes.",
    "editor.completeFields": "Complete the highlighted fields before saving.",
    "editor.connection": "Please check your connection and try again.",
    "editor.invalidImage": "Use JPG, PNG or WebP under 2 MB.",
    "editor.readImage": "Could not read this image.",
    "editor.storagePath": "Storage did not return a protected image path.",
    "editor.imagePreview": "{label} preview",
    "editor.upload": "Upload",
    "editor.remove": "Remove",
    "editor.uploadFailed": "Upload failed.",
    "editor.imageHelp": "JPG, PNG or WebP · 2 MB max",
    "editor.colorBlue": "Blue",
    "editor.colorDark": "Dark",
    "editor.colorPurple": "Purple",
    "editor.colorGreen": "Green",
    "editor.colorWarm": "Warm",
    "editor.templateMinimal": "Minimal",
    "editor.templateGallery": "Gallery",
    "editor.templateCards": "Cards",
    "editor.templateBlog": "Blog",
    "editor.templateCreative": "Creative",
    "editor.templateAgency": "Agency",
    "editor.templateShowcase": "Showcase",
    "editor.validationTitle": "Title must contain at least 3 characters.",
    "editor.validationImageUrl": "Invalid image URL.",
    "editor.validationSocialDuplicate": "Each social platform can only be added once.",
    "editor.validationEmail": "Enter a valid email address.",
    "editor.validationInvalid": "Check the highlighted field.",
    "card.published": "Published",
    "card.draft": "Draft",
    "card.moreActions": "More actions for {title}",
    "card.copyUrl": "Copy public URL",
    "card.delete": "Delete",
    "card.updated": "Updated {date}",
    "card.view": "View",
    "card.private": "Private",
    "public.portrait": "Portrait of {title}",
    "public.logo": "Portfolio logo",
    "public.socialProfiles": "Social profiles",
    "public.selectedWork": "Selected work",
    "public.projectPreview": "Preview of {title}",
    "public.caseStudy": "View case study",
    "public.contact": "Contact",
    "public.contactTitle": "Let’s work together",
    "public.contactDescription": "Have a thoughtful project in mind? Send a short note and I’ll reply as soon as I can.",
    "public.email": "Email",
    "public.yourName": "Your name",
    "public.yourEmail": "Your email",
    "public.yourMessage": "Your message",
    "public.projectHint": "A little about your project",
    "public.sendEmail": "Send an email",
    "preview.live": "Live preview",
    "landing.demoBio": "Independent designer shaping lucid product experiences.",
    "landing.demoWork": "Selected work",
    "landing.demoAbout": "About",
  },
  ru: {
    "language.label": "Язык интерфейса",
    "language.russian": "Русский",
    "language.english": "English",
    "theme.toDark": "Включить тёмную тему",
    "theme.toLight": "Включить светлую тему",
    "common.dashboard": "Панель управления",
    "common.loading": "Загрузка…",
    "common.cancel": "Отменить",
    "common.save": "Сохранить",
    "common.back": "Назад",
    "auth.signupTitle": "Создайте аккаунт",
    "auth.signinTitle": "С возвращением",
    "auth.signupDescription": "Начните собирать портфолио в защищённом рабочем пространстве.",
    "auth.signinDescription": "Войдите, чтобы продолжить работу над своим портфолио.",
    "auth.name": "Имя",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.signup": "Создать аккаунт",
    "auth.signin": "Войти",
    "auth.wait": "Подождите…",
    "auth.hasAccount": "Уже есть аккаунт?",
    "auth.noAccount": "Впервые в Portfolio Pro?",
    "auth.verifyEmail": "Проверьте почту и подтвердите адрес, затем войдите в Portfolio Pro.",
    "auth.invalidEmail": "Введите корректный email.",
    "auth.passwordLength": "Пароль должен содержать минимум 8 символов.",
    "auth.nameLength": "Введите имя минимум из 2 символов.",
    "auth.invalidData": "Проверьте введённые данные.",
    "auth.runtimeError": "Эта форма доступна только во внешнем Supabase runtime.",
    "auth.requestError": "Не удалось завершить аутентификацию.",
    "landing.login": "Войти",
    "landing.start": "Начать работу",
    "landing.eyebrow": "Конструктор портфолио для осмысленной работы",
    "landing.titleBefore": "Представьте свою работу",
    "landing.titleAccent": "ясно.",
    "landing.description": "Спокойный и мощный инструмент для дизайнеров, авторов и независимых студий. Создайте портфолио, которое узнают как ваше.",
    "landing.create": "Создать портфолио",
    "landing.how": "Как это работает",
    "landing.noCode": "Без кода",
    "landing.publish": "Публикация за минуты",
    "landing.evolve": "Растёт вместе с вами",
    "landing.sectionEyebrow": "Для работы, которая стоит за результатом",
    "landing.sectionTitle": "Сфокусированное пространство для сильного первого впечатления.",
    "landing.featureLayoutsTitle": "Четыре продуманных макета",
    "landing.featureLayoutsText": "Minimal, Gallery, Cards и Blog — каждый настроен под свой творческий голос.",
    "landing.featureVisualTitle": "Ваш визуальный язык",
    "landing.featureVisualText": "Настраивайте цвет, типографику, биографию и социальные ссылки без единой строчки кода.",
    "landing.featureControlTitle": "Полный контроль",
    "landing.featureControlText": "Сразу видьте изменения, спокойно проверяйте их и сохраняйте, когда будете готовы.",
    "dashboard.unauthTitle": "Ваше рабочее пространство ждёт.",
    "dashboard.unauthDescription": "Войдите, чтобы создавать и управлять опубликованными работами.",
    "dashboard.continueEmail": "Продолжить с email",
    "dashboard.continueManus": "Продолжить с Manus",
    "dashboard.logout": "Выйти",
    "dashboard.portfolios": "Портфолио",
    "dashboard.sidebarTitle": "Сделайте его по-настоящему своим.",
    "dashboard.sidebarDescription": "Добавьте краткое описание, запоминающийся адрес и визуальный язык.",
    "dashboard.eyebrow": "Ваше пространство",
    "dashboard.descriptionEmpty": "Дом для работы, по которой вас будут помнить.",
    "dashboard.descriptionCount": "В вашей студии: {count} портфолио.",
    "dashboard.create": "Новое портфолио",
    "dashboard.creating": "Создаём…",
    "dashboard.loadError": "Не удалось загрузить портфолио. Обновите страницу и попробуйте ещё раз.",
    "dashboard.deleteConfirm": "Удалить это портфолио? Действие нельзя отменить.",
    "dashboard.emptyTitle": "Начните с чистого листа.",
    "dashboard.emptyDescription": "Создайте первое портфолио, а затем настройте его в live-редакторе.",
    "dashboard.createFirst": "Создать портфолио",
    "dashboard.createError": "Не удалось открыть созданное портфолио.",
    "editor.saved": "Изменения сохранены",
    "editor.cancel": "Отменить",
    "editor.saving": "Сохраняем",
    "editor.save": "Сохранить",
    "editor.notFound": "Это портфолио не найдено.",
    "editor.backDashboard": "Вернуться к портфолио",
    "editor.untitled": "Портфолио без названия",
    "editor.projects": "Проекты",
    "editor.view": "Открыть",
    "editor.uploading": "Загрузка",
    "editor.profileTitle": "Ваш профиль",
    "editor.profileDescription": "Сформируйте историю, с которой знакомятся посетители.",
    "editor.portfolioTitle": "Название портфолио",
    "editor.biography": "О себе",
    "editor.avatar": "Аватар",
    "editor.logo": "Логотип",
    "editor.publicUrl": "Публичная ссылка",
    "editor.publicUrlDescription": "Создаётся из названия, но вы можете настроить её сами.",
    "editor.artDirection": "Визуальный стиль",
    "editor.artDescription": "Каждое изменение сразу отображается справа.",
    "editor.template": "Шаблон",
    "editor.colorScheme": "Цветовая схема",
    "editor.typography": "Типографика",
    "editor.socialLinks": "Социальные ссылки",
    "editor.socialDescription": "Добавьте до пяти мест, где вас можно найти.",
    "editor.add": "Добавить",
    "editor.removeSocial": "Удалить социальную ссылку",
    "editor.publish": "Опубликовать это портфолио",
    "editor.publishDescription": "Если выключить переключатель, публичная ссылка будет возвращать страницу 404.",
    "editor.completeUpload": "Завершите загрузку изображения перед сохранением.",
    "editor.completeFields": "Заполните выделенные поля перед сохранением.",
    "editor.connection": "Проверьте подключение и попробуйте ещё раз.",
    "editor.invalidImage": "Загрузите JPG, PNG или WebP размером до 2 МБ.",
    "editor.readImage": "Не удалось прочитать изображение.",
    "editor.storagePath": "Хранилище не вернуло защищённый путь изображения.",
    "editor.imagePreview": "Превью: {label}",
    "editor.upload": "Загрузить",
    "editor.remove": "Удалить",
    "editor.uploadFailed": "Не удалось загрузить изображение.",
    "editor.imageHelp": "JPG, PNG или WebP · до 2 МБ",
    "editor.colorBlue": "Синяя",
    "editor.colorDark": "Тёмная",
    "editor.colorPurple": "Фиолетовая",
    "editor.colorGreen": "Зелёная",
    "editor.colorWarm": "Тёплая",
    "editor.templateMinimal": "Минималистичный",
    "editor.templateGallery": "Галерея",
    "editor.templateCards": "Карточки",
    "editor.templateBlog": "Блог",
    "editor.templateCreative": "Креативный",
    "editor.templateAgency": "Агентство",
    "editor.templateShowcase": "Витрина",
    "editor.validationTitle": "Название должно содержать минимум 3 символа.",
    "editor.validationImageUrl": "Некорректный URL изображения.",
    "editor.validationSocialDuplicate": "Каждую социальную платформу можно добавить только один раз.",
    "editor.validationEmail": "Введите корректный email.",
    "editor.validationInvalid": "Проверьте выделенное поле.",
    "card.published": "Опубликовано",
    "card.draft": "Черновик",
    "card.moreActions": "Дополнительные действия для «{title}»",
    "card.copyUrl": "Скопировать публичную ссылку",
    "card.delete": "Удалить",
    "card.updated": "Обновлено: {date}",
    "card.view": "Открыть",
    "card.private": "Приватно",
    "public.portrait": "Портрет: {title}",
    "public.logo": "Логотип портфолио",
    "public.socialProfiles": "Профили в социальных сетях",
    "public.selectedWork": "Избранные работы",
    "public.projectPreview": "Превью: {title}",
    "public.caseStudy": "Открыть кейс",
    "public.contact": "Контакты",
    "public.contactTitle": "Давайте работать вместе",
    "public.contactDescription": "Есть идея для проекта? Отправьте короткое сообщение — я отвечу при первой возможности.",
    "public.email": "Email",
    "public.yourName": "Ваше имя",
    "public.yourEmail": "Ваш email",
    "public.yourMessage": "Ваше сообщение",
    "public.projectHint": "Коротко расскажите о проекте",
    "public.sendEmail": "Отправить письмо",
    "preview.live": "Live preview",
    "landing.demoBio": "Независимый дизайнер, создающий ясные цифровые продукты.",
    "landing.demoWork": "Избранные работы",
    "landing.demoAbout": "Обо мне",
  },
} as const;

export type TranslationKey = keyof typeof messages.en;

type LanguageContextValue = {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: TranslationKey, values?: TranslationValues) => string;
};

function interpolate(message: string, values?: TranslationValues): string {
  if (!values) return message;

  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    message,
  );
}

const LanguageContext = createContext<LanguageContextValue>({
  locale: "en",
  setLocale: () => undefined,
  t: (key, values) => interpolate(messages.en[key], values),
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    const storedLocale = typeof window === "undefined" ? null : window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
    const browserLocale = typeof navigator === "undefined" ? undefined : navigator.language;
    return resolveLocale(storedLocale, browserLocale);
  });

  useEffect(() => {
    document.documentElement.lang = locale;
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, locale);
  }, [locale]);

  const value = useMemo<LanguageContextValue>(() => ({
    locale,
    setLocale,
    t: (key, values) => interpolate(messages[locale][key], values),
  }), [locale]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  return useContext(LanguageContext);
}
